### ISSUE TITLE
CI's Download latest Sequoia IPSW broken

### ISSUE THREAD

**Issue by bunnyblueair** [dortania/MetallibSupportPkg#1]
https://github.com/dortania/MetallibSupportPkg/actions/runs/11376321259 Download latest Sequoia IPSW   task has error
it's bug?

**Comment by khronokernel** [comment]
Hello, 

Good catch. Less a critical error, but an issue non the less. AppleDB doesn't have any new IPSWs for us to patch against, which is why the error pops up.

Thanks for the report!
