### ISSUE TITLE
Where is pkg 15.2-24C100

### ISSUE THREAD

**Issue by antoniotvc** [dortania/MetallibSupportPkg#2]
MetallibSupportPkg-15.2-24C100.pkg is not for download and i have an error when patch Sequoia 15.2(24C100)
![Captura de pantalla 2024-12-11 a las 7 43 38](https://github.com/user-attachments/assets/4ec90fa8-4996-40ad-b9a0-4f95254f8f79)

**Comment by jyouell** [comment]
Same issue Sequoia 15.2 on Mac mini 2014.

**Comment by khronokernel** [comment]
SSL error on GitHub's end, restarted the workflow:
https://github.com/dortania/MetallibSupportPkg/actions/runs/12244368109

**Comment by khronokernel** [comment]
https://github.com/dortania/MetallibSupportPkg/releases/tag/15.2-24C100
